project:
  type: book

book:
  title: "Linear Algebra"
  subtitle: "MATH2210-notes"
  author: Qianruo Tan
  date: today

chapters:
  - index.qmd
  - Tan_definitions.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex


execute:
  freeze: auto