project:
  type: website

website:
  title: "MATH2210-notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Tan Definitions
        href: Tan_definitions.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true