project:
  type: book

book:
  title: "Linear Algebra"
  subtitle: "MATH2210-notes"
  author: Qianruo Tan
  date: today

chapters:
  - index.qmd
  - Tan_definitions.qmd

format:
  html:
    theme: cosmo

execute:
  freeze: auto